 # Creating Numpy array by passing a Python tuple

In [41]:
import numpy as np

In [42]:
sample_list = [1,2,3]

In [43]:
list_array = np.array(sample_list)

In [44]:
tup = (1,2,3)

In [45]:
my_tup_array = np.array(tup)
list_array.shape

(3,)

In [46]:
print(list_aray)

[1 2 3]


In [47]:
print(my_tup_array)

[1 2 3]


# Time comparison of a NumPy operation and a corresponding Python code

In [48]:
#multiplication using normal Python way
def multiply_loops(A,B):
    c = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            c[i, j] = 0
            
            for k in range(A.shape[1]):
                n = A[i,k]*B[k,j]
                c[i ,j] += n
                
    return c 
        
        
    
    

In [49]:
#multiplication using NumPy's vector multiplication way.

def multiply_vector(A,B):
    return A @ B


In [95]:
X = np.random.rand(100,90)
Y = np.random.random((90,80))
print(X,Y)

[[0.98453322 0.43460693 0.74150897 ... 0.87780603 0.72999313 0.94588564]
 [0.16572332 0.30993434 0.61405982 ... 0.96908349 0.14732076 0.55376867]
 [0.27050356 0.35654216 0.68442423 ... 0.61998532 0.3208745  0.57043205]
 ...
 [0.13205989 0.79160376 0.38391423 ... 0.52575304 0.6990233  0.30849085]
 [0.45138154 0.5237616  0.82672139 ... 0.07536813 0.30570958 0.20278675]
 [0.75784902 0.95963142 0.85217797 ... 0.24420285 0.74499499 0.81281468]] [[0.33821526 0.2079561  0.35016184 ... 0.63323555 0.47888949 0.68060061]
 [0.7177991  0.2216195  0.79262381 ... 0.52775405 0.9438426  0.77623594]
 [0.37861962 0.92683565 0.53915274 ... 0.2638062  0.82906634 0.96334828]
 ...
 [0.92467405 0.27680764 0.9752705  ... 0.93372041 0.30747126 0.68539931]
 [0.01446751 0.20724991 0.17977622 ... 0.1554806  0.16069954 0.00528518]
 [0.94906449 0.61220561 0.49406737 ... 0.88610102 0.55623724 0.6112198 ]]


In [51]:
%timeit multiply_loops(X, Y)
%timeit multiply_vector(X,Y)

405 ms ± 1.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
129 µs ± 11.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#  NumPy - Arrays - Special Types of Arrays - Array filled with specific value

## Creating NumPy array with all its elements values as zero (using zeros() function of NumPy)

In [53]:
#Create a tuple indicating dimensions of the desired array
tup_dim = (3,4)

In [58]:
'''
Now, create your NumPy array by passing the above tuple 
(tup_dim) to zeros() function below

'''

my_zeros_array = np.zeros(tup_dim , dtype =np.int16)
print(my_zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


##  Creating NumPy array with all its elements values as one (using ones() function of NumPy)

In [57]:
#Create a tuple indicating dimensions of the desired array
tup_dim = (3,4)

In [59]:
'''
Now, create your NumPy array by passing the above tuple (tup_dim) to 
ones() function below

'''
my_ones_array = np.ones(tup_dim, dtype = np.int16)
print(my_ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## Creating NumPy array with all its elements values as a specific given value (using full() function of NumPy)

In [61]:
'''
Now, create your NumPy array by passing the above tuple (tup_dim) to full() function below, along with the 
desired value that you want the array to be filled with (e.g. say value 7)

'''

my_seven_array = np.full(tup_dim , 7, dtype = np.int16)

print(my_seven_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


## Creating Identity matrix or array

"""
Identity matrix (array) is a square matrix with all its elements as zero (0) except for the diagonal elements whose value is one (1). That is, all the main diagonal values are 1s (one).

You can create an Identity matrix by using numpy's identity() function by passing the desired dimension of the matrix (array) and the data type required.

e.g. np.identity(2, dtype=float) will create a 2x2 matrix with all its values as 0.0 except for the diagonal values which will be 1.0

"""



In [65]:
my_identity_array = np.identity(4, dtype = np.float64)
print(my_identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Numpy - Arrays - Special Types of Arrays - Array with Random Values

Below are few more special NumPy arrays which you can create to contain random values.

For example:

1. NumPy array with all its elements values as random values (using random.rand() function of NumPy)
2. NumPy array with all its elements values as uninitialized values (initialized with some random values which you are not aware of - using empty() function of NumPy)

In [105]:
'''
Create your NumPy array by passing the above the desired dimensions
of the array (say (3,4)) to random.rand() function below

'''
my_rand_array = np.random.rand(3,4)
print(my_rand_array)


[[0.21235297 0.55960935 0.29920399 0.85138542]
 [0.78146841 0.04052046 0.87904981 0.73641387]
 [0.4348942  0.04941379 0.26655949 0.36067324]]


In [104]:
'''
NumPy array with all its elements values as uninitialized values (initialized with some random values which you are not 
aware of - using the empty() function of NumPy)

'''
my_uninitialized_array = np.empty((3,4))
print(my_uninitialized_array)

[[0.28961052 0.70872951 0.01210648 0.0356191 ]
 [0.02299172 0.90726761 0.42555599 0.16684941]
 [0.95446814 0.385983   0.31544842 0.19538158]]


## Numpy - Arrays - Special Types of Arrays - Array with values within a particular range

Below are few more special NumPy arrays that you can create, having values within a particular given range.

For example, you can create a NumPy array in the below ways:

1.By passing a range of values (using arange() function of NumPy)

2.By passing an equally spaced range of values (using linspace() function of NumPy)

### Creating a NumPy array by passing a range of values (using arange() function of NumPy)
  
  To create this NumPy array, pass the start value (10), end value (30) and the gap value 5, to the arange() function below


In [116]:
my_range_array = np.arange(10,30,5)
print(my_range_array)

[10 15 20 25]


### Creating a NumPy array by passing an equally spaced range of values (using linspace() function of NumPy)

Suppose you want to create a NumPy array whose values should lie between 0 and 5/3 and the consecutive values should have an equal amount of gap between them (equally spaced values).

To create this NumPy array, pass the start value (0), end value (5/3), and the total number of values you want (say 6), to the linspace() function below

he above NumPy array my_spaced_array will have total of 6 values with values ranging between 0 and 5/3 (**including 5/3**) and having an equal amount of gap between the consecutive values.



In [120]:
my_spaced_array = np.linspace(0,5/3, 6)
print(my_spaced_array)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


# NumPy - Arrays - Attributes of a NumPy Array

NumPy array (ndarray class) is the most used construct of NumPy in Machine Learning and Deep Learning. Let us look into some important attributes of this NumPy array.

Let us create a Numpy array first, say, array_A.

Pass the above list to `array()` function of NumPy

In [131]:
arra_A = np.array([[3,4,6], [0,8,1]])

Now, let us understand some important attributes of ndarray object using the above-created array  `array_A` 

(1) ndarray.ndim

`ndim` represents the number of dimensions (axes) of the ndarray.

e.g. for this 2-dimensional array [ [3,4,6], [0,8,1]], value of ndim will be 2. This ndarray has two dimensions (axes) - rows (axis=0) and columns (axis=1)

(2) ndarray.shape

shape is a tuple of integers representing the size of the ndarray in each dimension.

e.g. for this 2-dimensional array [ [3,4,6], [0,8,1]], value of shape will be (2,3) because this ndarray has two dimensions - rows and columns - and the number of rows is 2 and the number of columns is 3

(3) ndarray.size

size is the total number of elements in the ndarray. It is equal to the product of elements of the shape. e.g. for this 2-dimensional array [ [3,4,6], [0,8,1]], shape is (2,3), size will be product (multiplication) of 2 and 3 i.e. (2*3) = 6. Hence, the size is 6.

(4) ndarray.dtype

dtype tells the data type of the elements of a NumPy array. In NumPy array, all the elements have the same data type.

e.g. for this NumPy array [ [3,4,6], [0,8,1]], dtype will be int64

(5) ndarray.itemsize

`itemsize` returns the size (in bytes) of each element of a NumPy array.

e.g. for this NumPy array [ [3,4,6], [0,8,1]], itemsize will be 8, because this array consists of integers and size of integer (in bytes) is 8 bytes.

In [132]:
my_array = np.array([ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ])

In [133]:
print(my_array)

[[ 1  4  5  6]
 [ 7  8  9 10]
 [11 12 14 16]]


In [143]:
my_array.dtype

dtype('int64')

In [145]:
my_array.size

12

# Numpy - Arrays - Loading a text file data using NumPy's loadtxt() function - Step 1

Although Pandas provides better ways and constructs to load a dataset from various sources like files, databases, etc. we should also know the NumPy constructs for the same.

There are two ways (constructs) in NumPy to load data from a text file:

(1) using `loadtxt()` function

(2) using `genfromtxt()` function

`loadtxt()` function provides less flexibility, whereas genfromtxt() function provides more flexibility.

For example, `genfromtxt()` function also handles the missing values kind of scenarios in the loaded dataset, whereas loadtxt() function doesn't.

`name_arr, address_arr, zipcode_arr = np.loadtxt('my_file.txt', skiprows=2, unpack=True)`

The above piece of code will load the data from my_file.txt text file.

skiprows=2 means, skip the first two rows of the my_file.txt file while loading the data.

unpack=True means, unpack the columns of the dataset being loaded and return the data of each column separately in separate arrays ( name column data in name_arr array, address column data in address_arr array, zipcode column data in zipcode_arr array).

unpack=False means, return only a single array as output from the loadtxt() function.

# Numpy - Arrays - Loading a text file data using NumPy's loadtxt() function - Step 2

In [153]:
import os 

In [152]:
import pandas as pd
# defining housing.csv file path
HOUSING_PATH =  '/cxldata/datasets/project/housing'
# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)

In [155]:
#load using Numpy

FILE = 'housing_short.csv'

In [156]:
def load_housing_data(file = FILE ):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)

loadtxt() function parameters:

**first parameter** - file. It is the name of the file from which the data is to be loaded.

**second parameter** - data type dtype of columns of the loaded csv file housing_short.csv. It is a Python dictionary with key as names of the columns, and values as the data types of these respective columns e.g. f8, |S15, etc.

'f8' means 64-bit floating-point number

'|S15' -means a string of length of 15 characters

**third parameter** - delimiter. It is the character by which values in a row of our csv file are separated. For example, in our case values of a row of our csv file - housing_short.csv - are separated by ',' (comma)

**fourth parameter** - skiprows. You can specify here, how many initial rows of the csv file you want to skip loading. E.g. you may want to skip the first row of this csv file, as it may contain header information in the first row, which you may not want to load.

**fifth parameter** - unpack. When unpack is True, the returned array is transposed, so that arguments may be unpacked using x, y, z = loadtxt(...). When used with a structured data-type, arrays are returned for each field. The default value for unpack is False. But here we are returning the individual arrays so we have kept it here asTrue.

Please call the above defined load_housing_data() function, which returns various column values as NumPy arrays

In [159]:
longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()

In [160]:
print(longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr )

[-122.23 -122.22 -122.24 -122.25 -122.25] [37.88 37.86 37.85 37.85 37.85] [41. 21. 52. 52. 52.] [ 880. 7099. 1467. 1274. 1627.] [ 129. 1106.  190.  235.  280.] [ 322. 2401.  496.  558.  565.] [ 126. 1138.  177.  219.  259.] [8.3252 8.3014 7.2574 5.6431 3.8462] [452600. 358500. 352100. 341300. 342200.] [b'NEAR BAY' b'NEAR BAY' b'NEAR BAY' b'NEAR BAY' b'NEAR BAY']


# Numpy - Arrays - Loading a text file data using NumPy's genfromtxt() function 